### ISSUE TITLE
Plan to update `networkx` dependency?

### ISSUE THREAD

**Issue by boothby** [dwavesystems/dwave-networkx#221]
The `networkx` dependency has been pinned at 2.4 for quite a while, which is quite outdated (currently v2.8.3).  The Python support window is sliding, and `networkx2.4` officially supports py3.5 through py3.8; `networkx2.8.3` supports py3.8 through py3.10.  The NetworkX deprecation policy is that breaking changes can be made over the course of two minor releases, so maintaining this pinned version may be accumulating a backlog of unnoticed deprecations.  And, of course, we're missing out on performance improvements and bugfixes.

Updating this pin will require some coordination between `dwave-networkx`, `minorminer`, and `dimod`; I'm sure that this list is incomplete.  While there's no immediate need, it would be good to do this sooner rather than later.

**Comment by randomir** [comment]
We use `networkx>=2.4,<3.0` across Ocean packages for `install_requires`, and usually unpin `networkx` in (dev/test) `requirements.txt`.

We keep it unpinned if we use it minimally, and any version will probably work just fine. For critical dependencies we actually **sweep through a range** of versions in CI. That approach might be fitting here since dnx relies heavily on nx. For an example, see [here](https://github.com/dwavesystems/dwave-cloud-client/blob/95f418eb2395ce8033e975728364b62fcf958c5f/.circleci/config.yml#L33-L41).

A simpler approach might be to pin `networkx` based on the python version used in tests. For an example of that, see [here](https://github.com/dwavesystems/dwave-hybrid/blame/master/requirements.txt).

**Comment by arcondello** [comment]
Does anyone know if the sdist install of NetworkX 2.8.x works with Python 3.7? If so, it's probably fine to bump our minimum version in all of the relevant packages. Or use version tags.

That said, there are many packages that have a NetworkX dependency (most recently https://github.com/dwavesystems/dwave-samplers) so updating them all will be a pain. We should probably consider removing NetworkX as a dependency for the packages that only use it for one or two utility functions, to make maintenance easier.

**Comment by kevinchern** [comment]
Bumping this issue: with dwave-networkx==0.8.14, plotting functions don't behave as expected (missing edges).
For what it's worth:
* networkx==2.6.3 is also buggy (the version specified in dwave-samplers).
* networkx==2.8.8 works for me 😛

**Comment by vgoliber** [comment]
I'm seeing warnings on demos using the networkx drawing functionality (maximum-cut for example), which a more recent version eliminates.

**Comment by arcondello** [comment]
[dwave-ocean-sdk 6.8.0](https://github.com/dwavesystems/dwave-ocean-sdk/releases/tag/6.8.0) supports NetworkX 3.0, see also https://github.com/dwavesystems/dwave-system/issues/511.

For this package specifically, https://github.com/dwavesystems/dwave-networkx/pull/230 added testing with the latest NetworkX.

It should be safe to update the requirements for those demos. Closing this issue.
